[package]
name = "medieval"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[lib]
name = "medieval_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "medieval"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
medieval-core = { path = "../crates/medieval-core" }
medieval-save = { path = "../crates/medieval-save" }
tauri = { version = "2", features = [] }
