[package]
name = "medieval"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[lib]
name = "medieval_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "medieval"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
medieval-core = { path = "../crates/medieval-core" }
tauri = { version = "2", features = ["unstable"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
medieval-renderer = { path = "../crates/medieval-renderer" }
serde = { version = "1", features = ["derive"] }
wgpu = "30.0.1"
