[package]
name = "medieval-renderer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
medieval-core = { path = "../medieval-core" }
serde.workspace = true
serde_json.workspace = true
wgpu = "30.0.1"
three-d-formats = { git = "https://github.com/moritzbrantner/3d-lab", rev = "5340bdf31de6761ed16737dd6d19da2431172fd6" }
